package Interfaces;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Classes.CarsPlant;
/**
 *
 * @author marti
 */
public class GUI extends javax.swing.JFrame {
    
    private CarsPlant maserati;
    /**
     * Creates new form GUI
     */
    public GUI(CarsPlant maserati) {
        this.maserati = maserati;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Menu = new javax.swing.JPanel();
        Bugatti = new javax.swing.JPanel();
        ChasisEmployeeQtty = new javax.swing.JLabel();
        AssemblerEmployeeQttyTitle = new javax.swing.JLabel();
        EmployeeQtty = new javax.swing.JLabel();
        ChasisEmployeeQttyLess = new javax.swing.JButton();
        ChasisEmployeeQttyPlus = new javax.swing.JButton();
        BodyworksEmployeeQtty = new javax.swing.JLabel();
        BodyworksEmployeeQttyLess = new javax.swing.JButton();
        BodyworksEmployeeQttyPlus = new javax.swing.JButton();
        MotorsEmployeeQtty = new javax.swing.JLabel();
        MotorsEmployeeQttyLess = new javax.swing.JButton();
        MotorsEmployeeQttyPlus = new javax.swing.JButton();
        WheelsEmployeeQtty = new javax.swing.JLabel();
        WheelsEmployeeQttyLess = new javax.swing.JButton();
        WheelsEmployeeQttyPlus = new javax.swing.JButton();
        AccessoriesEmployeeQtty = new javax.swing.JLabel();
        AccessoriesEmployeeQttyLess = new javax.swing.JButton();
        AccessoriesEmployeeQttyPlus = new javax.swing.JButton();
        AssemblerEmployeeQtty = new javax.swing.JLabel();
        AssemblerEmployeeQttyLess = new javax.swing.JButton();
        AssemblerEmployeeQttyPlus = new javax.swing.JButton();
        EmployeeQttyTitle = new javax.swing.JLabel();
        BodyworksEmployeeQttyTitle = new javax.swing.JLabel();
        MotorsEmployeeQttyTitle = new javax.swing.JLabel();
        WheelsEmployeeQttyTitle = new javax.swing.JLabel();
        AccessoriesEmployeeQttyTitle = new javax.swing.JLabel();
        PlantDirectorJob = new javax.swing.JLabel();
        ChasisQtty = new javax.swing.JLabel();
        StandardCarsQttyTitle = new javax.swing.JLabel();
        BodyworksQtty = new javax.swing.JLabel();
        MotorsQtty = new javax.swing.JLabel();
        WheelsQtty = new javax.swing.JLabel();
        AccessoriesQtty = new javax.swing.JLabel();
        StandardCarsQtty = new javax.swing.JLabel();
        BodyworksQttyTitle = new javax.swing.JLabel();
        MotorsQttyTitles = new javax.swing.JLabel();
        WheelsQttyTitle = new javax.swing.JLabel();
        AccessoriesQttyTitle = new javax.swing.JLabel();
        MaxAccessoriesQttyTitle = new javax.swing.JLabel();
        AccessoriesCarsQttyTitle = new javax.swing.JLabel();
        AccessoriesCarsQtty = new javax.swing.JLabel();
        ChasisQttyTitle = new javax.swing.JLabel();
        MaxChasisQttyTitle = new javax.swing.JLabel();
        MaxBodyworksQttyTitle = new javax.swing.JLabel();
        MaxMotorsQttyTitles = new javax.swing.JLabel();
        MaxWheelsQttyTitle = new javax.swing.JLabel();
        MaxChasisQtty = new javax.swing.JLabel();
        MaxBodyworksQtty = new javax.swing.JLabel();
        MaxMotorsQtty = new javax.swing.JLabel();
        MaxWheelsQtty = new javax.swing.JLabel();
        MaxAccessoriesQtty = new javax.swing.JLabel();
        DaysLeft = new javax.swing.JLabel();
        PlantTitle = new javax.swing.JLabel();
        DaysLeftTitle = new javax.swing.JLabel();
        OpManagerTitle = new javax.swing.JLabel();
        EmployeeTitle = new javax.swing.JLabel();
        PlantDirectorTitle = new javax.swing.JLabel();
        ChasisEmployeeQttyTitle = new javax.swing.JLabel();
        PlantDirectorJobTitle = new javax.swing.JLabel();
        OpManagerJob = new javax.swing.JLabel();
        OpManagerJobTitle = new javax.swing.JLabel();
        OpManagerFaults = new javax.swing.JLabel();
        OpManagerFaultsTitle = new javax.swing.JLabel();
        OpManagerMoneyTaken = new javax.swing.JLabel();
        OpManagerMoneyTakenTitle = new javax.swing.JLabel();
        WarehouseTitle1 = new javax.swing.JLabel();
        Maserati = new javax.swing.JPanel();
        ChasisEmployeeQtty1 = new javax.swing.JLabel();
        AssemblerEmployeeQttyTitle1 = new javax.swing.JLabel();
        EmployeeQtty1 = new javax.swing.JLabel();
        ChasisEmployeeQttyLess1 = new javax.swing.JButton();
        ChasisEmployeeQttyPlus1 = new javax.swing.JButton();
        BodyworksEmployeeQtty1 = new javax.swing.JLabel();
        BodyworksEmployeeQttyLess1 = new javax.swing.JButton();
        BodyworksEmployeeQttyPlus1 = new javax.swing.JButton();
        MotorsEmployeeQtty1 = new javax.swing.JLabel();
        MotorsEmployeeQttyLess1 = new javax.swing.JButton();
        MotorsEmployeeQttyPlus1 = new javax.swing.JButton();
        WheelsEmployeeQtty1 = new javax.swing.JLabel();
        WheelsEmployeeQttyLess1 = new javax.swing.JButton();
        WheelsEmployeeQttyPlus1 = new javax.swing.JButton();
        AccessoriesEmployeeQtty1 = new javax.swing.JLabel();
        AccessoriesEmployeeQttyLess1 = new javax.swing.JButton();
        AccessoriesEmployeeQttyPlus1 = new javax.swing.JButton();
        AssemblerEmployeeQtty1 = new javax.swing.JLabel();
        AssemblerEmployeeQttyLess1 = new javax.swing.JButton();
        AssemblerEmployeeQttyPlus1 = new javax.swing.JButton();
        EmployeeQttyTitle1 = new javax.swing.JLabel();
        BodyworksEmployeeQttyTitle1 = new javax.swing.JLabel();
        MotorsEmployeeQttyTitle1 = new javax.swing.JLabel();
        WheelsEmployeeQttyTitle1 = new javax.swing.JLabel();
        AccessoriesEmployeeQttyTitle1 = new javax.swing.JLabel();
        PlantDirectorJob1 = new javax.swing.JLabel();
        ChasisQtty1 = new javax.swing.JLabel();
        StandardCarsQttyTitle1 = new javax.swing.JLabel();
        BodyworksQtty1 = new javax.swing.JLabel();
        MotorsQtty1 = new javax.swing.JLabel();
        WheelsQtty1 = new javax.swing.JLabel();
        AccessoriesQtty1 = new javax.swing.JLabel();
        StandardCarsQtty1 = new javax.swing.JLabel();
        BodyworksQttyTitle1 = new javax.swing.JLabel();
        MotorsQttyTitles1 = new javax.swing.JLabel();
        WheelsQttyTitle1 = new javax.swing.JLabel();
        AccessoriesQttyTitle1 = new javax.swing.JLabel();
        MaxAccessoriesQttyTitle1 = new javax.swing.JLabel();
        AccessoriesCarsQttyTitle1 = new javax.swing.JLabel();
        AccessoriesCarsQtty1 = new javax.swing.JLabel();
        ChasisQttyTitle1 = new javax.swing.JLabel();
        MaxChasisQttyTitle1 = new javax.swing.JLabel();
        MaxBodyworksQttyTitle1 = new javax.swing.JLabel();
        MaxMotorsQttyTitles1 = new javax.swing.JLabel();
        MaxWheelsQttyTitle1 = new javax.swing.JLabel();
        MaxChasisQtty1 = new javax.swing.JLabel();
        MaxBodyworksQtty1 = new javax.swing.JLabel();
        MaxMotorsQtty1 = new javax.swing.JLabel();
        MaxWheelsQtty1 = new javax.swing.JLabel();
        MaxAccessoriesQtty1 = new javax.swing.JLabel();
        DaysLeft1 = new javax.swing.JLabel();
        PlantTitle1 = new javax.swing.JLabel();
        DaysLeftTitle1 = new javax.swing.JLabel();
        OpManagerTitle1 = new javax.swing.JLabel();
        EmployeeTitle1 = new javax.swing.JLabel();
        PlantDirectorTitle1 = new javax.swing.JLabel();
        ChasisEmployeeQttyTitle1 = new javax.swing.JLabel();
        PlantDirectorJobTitle1 = new javax.swing.JLabel();
        OpManagerJob1 = new javax.swing.JLabel();
        OpManagerJobTitle1 = new javax.swing.JLabel();
        OpManagerFaults1 = new javax.swing.JLabel();
        OpManagerFaultsTitle1 = new javax.swing.JLabel();
        OpManagerMoneyTaken1 = new javax.swing.JLabel();
        OpManagerMoneyTakenTitle1 = new javax.swing.JLabel();
        WarehouseTitle2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proyecto 1 Sistemas Operativos");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 280, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 40));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Planta Bugatti");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, -1));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Planta Maserati");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 540));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", Menu);

        Bugatti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChasisEmployeeQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChasisEmployeeQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChasisEmployeeQtty.setText("1");
        Bugatti.add(ChasisEmployeeQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 50, 30));

        AssemblerEmployeeQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AssemblerEmployeeQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AssemblerEmployeeQttyTitle.setText("Empleados en ens.");
        Bugatti.add(AssemblerEmployeeQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 160, 30));

        EmployeeQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeQtty.setText("0");
        Bugatti.add(EmployeeQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 50, 30));

        ChasisEmployeeQttyLess.setText("-");
        ChasisEmployeeQttyLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChasisEmployeeQttyLessActionPerformed(evt);
            }
        });
        Bugatti.add(ChasisEmployeeQttyLess, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 50, 30));

        ChasisEmployeeQttyPlus.setText("+");
        ChasisEmployeeQttyPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChasisEmployeeQttyPlusActionPerformed(evt);
            }
        });
        Bugatti.add(ChasisEmployeeQttyPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 50, 30));

        BodyworksEmployeeQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BodyworksEmployeeQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BodyworksEmployeeQtty.setText("1");
        Bugatti.add(BodyworksEmployeeQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 50, 30));

        BodyworksEmployeeQttyLess.setText("-");
        BodyworksEmployeeQttyLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodyworksEmployeeQttyLessActionPerformed(evt);
            }
        });
        Bugatti.add(BodyworksEmployeeQttyLess, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 50, 30));

        BodyworksEmployeeQttyPlus.setText("+");
        BodyworksEmployeeQttyPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodyworksEmployeeQttyPlusActionPerformed(evt);
            }
        });
        Bugatti.add(BodyworksEmployeeQttyPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, 50, 30));

        MotorsEmployeeQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MotorsEmployeeQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MotorsEmployeeQtty.setText("1");
        Bugatti.add(MotorsEmployeeQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 50, 30));

        MotorsEmployeeQttyLess.setText("-");
        MotorsEmployeeQttyLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorsEmployeeQttyLessActionPerformed(evt);
            }
        });
        Bugatti.add(MotorsEmployeeQttyLess, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 50, 30));

        MotorsEmployeeQttyPlus.setText("+");
        MotorsEmployeeQttyPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorsEmployeeQttyPlusActionPerformed(evt);
            }
        });
        Bugatti.add(MotorsEmployeeQttyPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 50, 30));

        WheelsEmployeeQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WheelsEmployeeQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WheelsEmployeeQtty.setText("1");
        Bugatti.add(WheelsEmployeeQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 50, 30));

        WheelsEmployeeQttyLess.setText("-");
        WheelsEmployeeQttyLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheelsEmployeeQttyLessActionPerformed(evt);
            }
        });
        Bugatti.add(WheelsEmployeeQttyLess, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 50, 30));

        WheelsEmployeeQttyPlus.setText("+");
        WheelsEmployeeQttyPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheelsEmployeeQttyPlusActionPerformed(evt);
            }
        });
        Bugatti.add(WheelsEmployeeQttyPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 370, 50, 30));

        AccessoriesEmployeeQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesEmployeeQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessoriesEmployeeQtty.setText("1");
        Bugatti.add(AccessoriesEmployeeQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 50, 30));

        AccessoriesEmployeeQttyLess.setText("-");
        AccessoriesEmployeeQttyLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessoriesEmployeeQttyLessActionPerformed(evt);
            }
        });
        Bugatti.add(AccessoriesEmployeeQttyLess, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 50, 30));

        AccessoriesEmployeeQttyPlus.setText("+");
        AccessoriesEmployeeQttyPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessoriesEmployeeQttyPlusActionPerformed(evt);
            }
        });
        Bugatti.add(AccessoriesEmployeeQttyPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 420, 50, 30));

        AssemblerEmployeeQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AssemblerEmployeeQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AssemblerEmployeeQtty.setText("1");
        Bugatti.add(AssemblerEmployeeQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 50, 30));

        AssemblerEmployeeQttyLess.setText("-");
        AssemblerEmployeeQttyLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssemblerEmployeeQttyLessActionPerformed(evt);
            }
        });
        Bugatti.add(AssemblerEmployeeQttyLess, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, 50, 30));

        AssemblerEmployeeQttyPlus.setText("+");
        AssemblerEmployeeQttyPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssemblerEmployeeQttyPlusActionPerformed(evt);
            }
        });
        Bugatti.add(AssemblerEmployeeQttyPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, 50, 30));

        EmployeeQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        EmployeeQttyTitle.setText("Cantidad de empleados:");
        Bugatti.add(EmployeeQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 150, 30));

        BodyworksEmployeeQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BodyworksEmployeeQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BodyworksEmployeeQttyTitle.setText("Empleados en carrocería");
        Bugatti.add(BodyworksEmployeeQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 160, 30));

        MotorsEmployeeQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MotorsEmployeeQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MotorsEmployeeQttyTitle.setText("Empleados en motor");
        Bugatti.add(MotorsEmployeeQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 160, 30));

        WheelsEmployeeQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WheelsEmployeeQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WheelsEmployeeQttyTitle.setText("Empleados en ruedas");
        Bugatti.add(WheelsEmployeeQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 160, 30));

        AccessoriesEmployeeQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesEmployeeQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessoriesEmployeeQttyTitle.setText("Empleados en accesorios");
        Bugatti.add(AccessoriesEmployeeQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 160, 30));

        PlantDirectorJob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PlantDirectorJob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlantDirectorJob.setText("Trabajando");
        Bugatti.add(PlantDirectorJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 240, 30));

        ChasisQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChasisQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChasisQtty.setText("1");
        Bugatti.add(ChasisQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 50, 30));

        StandardCarsQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StandardCarsQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        StandardCarsQttyTitle.setText("Carros estándar:");
        Bugatti.add(StandardCarsQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 150, 30));

        BodyworksQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BodyworksQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BodyworksQtty.setText("1");
        Bugatti.add(BodyworksQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 50, 30));

        MotorsQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MotorsQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MotorsQtty.setText("1");
        Bugatti.add(MotorsQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 50, 30));

        WheelsQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WheelsQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WheelsQtty.setText("1");
        Bugatti.add(WheelsQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 50, 30));

        AccessoriesQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessoriesQtty.setText("1");
        Bugatti.add(AccessoriesQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 50, 30));

        StandardCarsQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StandardCarsQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StandardCarsQtty.setText("1");
        Bugatti.add(StandardCarsQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 50, 30));

        BodyworksQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BodyworksQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BodyworksQttyTitle.setText("Carrocerías:");
        Bugatti.add(BodyworksQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, 30));

        MotorsQttyTitles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MotorsQttyTitles.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MotorsQttyTitles.setText("Motores:");
        Bugatti.add(MotorsQttyTitles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, 30));

        WheelsQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WheelsQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        WheelsQttyTitle.setText("Ruedas:");
        Bugatti.add(WheelsQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 30));

        AccessoriesQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        AccessoriesQttyTitle.setText("Accesorios:");
        Bugatti.add(AccessoriesQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, 30));

        MaxAccessoriesQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxAccessoriesQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MaxAccessoriesQttyTitle.setText("Máx.");
        Bugatti.add(MaxAccessoriesQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 40, 30));

        AccessoriesCarsQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesCarsQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        AccessoriesCarsQttyTitle.setText("Carros con accesorios:");
        Bugatti.add(AccessoriesCarsQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 150, 30));

        AccessoriesCarsQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesCarsQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessoriesCarsQtty.setText("1");
        Bugatti.add(AccessoriesCarsQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 50, 30));

        ChasisQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChasisQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ChasisQttyTitle.setText("Chasis:");
        Bugatti.add(ChasisQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 30));

        MaxChasisQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxChasisQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MaxChasisQttyTitle.setText("Máx.");
        Bugatti.add(MaxChasisQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 40, 30));

        MaxBodyworksQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxBodyworksQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MaxBodyworksQttyTitle.setText("Máx.");
        Bugatti.add(MaxBodyworksQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 40, 30));

        MaxMotorsQttyTitles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxMotorsQttyTitles.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MaxMotorsQttyTitles.setText("Máx.");
        Bugatti.add(MaxMotorsQttyTitles, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 40, 30));

        MaxWheelsQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxWheelsQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MaxWheelsQttyTitle.setText("Máx.");
        Bugatti.add(MaxWheelsQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 40, 30));

        MaxChasisQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxChasisQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxChasisQtty.setText("1");
        Bugatti.add(MaxChasisQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 50, 30));

        MaxBodyworksQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxBodyworksQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxBodyworksQtty.setText("1");
        Bugatti.add(MaxBodyworksQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 50, 30));

        MaxMotorsQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxMotorsQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxMotorsQtty.setText("1");
        Bugatti.add(MaxMotorsQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 50, 30));

        MaxWheelsQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxWheelsQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxWheelsQtty.setText("1");
        Bugatti.add(MaxWheelsQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 50, 30));

        MaxAccessoriesQtty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxAccessoriesQtty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxAccessoriesQtty.setText("1");
        Bugatti.add(MaxAccessoriesQtty, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 50, 30));

        DaysLeft.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DaysLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaysLeft.setText("0");
        Bugatti.add(DaysLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 60, 50));

        PlantTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        PlantTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PlantTitle.setText("Bugatti");
        Bugatti.add(PlantTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 60));

        DaysLeftTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DaysLeftTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DaysLeftTitle.setText("Días para la entrega:");
        Bugatti.add(DaysLeftTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 200, 50));

        OpManagerTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        OpManagerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpManagerTitle.setText("Gerente de operaciones");
        Bugatti.add(OpManagerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 350, 50));

        EmployeeTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EmployeeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeTitle.setText("Empleados");
        Bugatti.add(EmployeeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 350, 50));

        PlantDirectorTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PlantDirectorTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlantDirectorTitle.setText("Director de la planta");
        Bugatti.add(PlantDirectorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 350, 50));

        ChasisEmployeeQttyTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChasisEmployeeQttyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChasisEmployeeQttyTitle.setText("Empleados en chasis");
        Bugatti.add(ChasisEmployeeQttyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 160, 30));

        PlantDirectorJobTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PlantDirectorJobTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlantDirectorJobTitle.setText("¿Qué está haciendo?");
        Bugatti.add(PlantDirectorJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 240, 30));

        OpManagerJob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpManagerJob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpManagerJob.setText("Trabajando");
        Bugatti.add(OpManagerJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 240, 30));

        OpManagerJobTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OpManagerJobTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpManagerJobTitle.setText("¿Qué está haciendo?");
        Bugatti.add(OpManagerJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 240, 30));

        OpManagerFaults.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpManagerFaults.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpManagerFaults.setText("0");
        Bugatti.add(OpManagerFaults, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 40, 30));

        OpManagerFaultsTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpManagerFaultsTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        OpManagerFaultsTitle.setText("Faltas:");
        Bugatti.add(OpManagerFaultsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 150, 30));

        OpManagerMoneyTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpManagerMoneyTaken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpManagerMoneyTaken.setText("0");
        Bugatti.add(OpManagerMoneyTaken, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 110, 30));

        OpManagerMoneyTakenTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpManagerMoneyTakenTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        OpManagerMoneyTakenTitle.setText("Dinero descontado:");
        Bugatti.add(OpManagerMoneyTakenTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 150, 30));

        WarehouseTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        WarehouseTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WarehouseTitle1.setText("Almacén");
        Bugatti.add(WarehouseTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 280, 50));

        jTabbedPane1.addTab("tab2", Bugatti);

        ChasisEmployeeQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChasisEmployeeQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChasisEmployeeQtty1.setText("1");

        AssemblerEmployeeQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AssemblerEmployeeQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AssemblerEmployeeQttyTitle1.setText("Empleados en ens.");

        EmployeeQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeQtty1.setText("0");

        ChasisEmployeeQttyLess1.setText("-");
        ChasisEmployeeQttyLess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChasisEmployeeQttyLess1ActionPerformed(evt);
            }
        });

        ChasisEmployeeQttyPlus1.setText("+");
        ChasisEmployeeQttyPlus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChasisEmployeeQttyPlus1ActionPerformed(evt);
            }
        });

        BodyworksEmployeeQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BodyworksEmployeeQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BodyworksEmployeeQtty1.setText("1");

        BodyworksEmployeeQttyLess1.setText("-");
        BodyworksEmployeeQttyLess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodyworksEmployeeQttyLess1ActionPerformed(evt);
            }
        });

        BodyworksEmployeeQttyPlus1.setText("+");
        BodyworksEmployeeQttyPlus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BodyworksEmployeeQttyPlus1ActionPerformed(evt);
            }
        });

        MotorsEmployeeQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MotorsEmployeeQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MotorsEmployeeQtty1.setText("1");

        MotorsEmployeeQttyLess1.setText("-");
        MotorsEmployeeQttyLess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorsEmployeeQttyLess1ActionPerformed(evt);
            }
        });

        MotorsEmployeeQttyPlus1.setText("+");
        MotorsEmployeeQttyPlus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorsEmployeeQttyPlus1ActionPerformed(evt);
            }
        });

        WheelsEmployeeQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WheelsEmployeeQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WheelsEmployeeQtty1.setText("1");

        WheelsEmployeeQttyLess1.setText("-");
        WheelsEmployeeQttyLess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheelsEmployeeQttyLess1ActionPerformed(evt);
            }
        });

        WheelsEmployeeQttyPlus1.setText("+");
        WheelsEmployeeQttyPlus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheelsEmployeeQttyPlus1ActionPerformed(evt);
            }
        });

        AccessoriesEmployeeQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesEmployeeQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessoriesEmployeeQtty1.setText("1");

        AccessoriesEmployeeQttyLess1.setText("-");
        AccessoriesEmployeeQttyLess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessoriesEmployeeQttyLess1ActionPerformed(evt);
            }
        });

        AccessoriesEmployeeQttyPlus1.setText("+");
        AccessoriesEmployeeQttyPlus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessoriesEmployeeQttyPlus1ActionPerformed(evt);
            }
        });

        AssemblerEmployeeQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AssemblerEmployeeQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AssemblerEmployeeQtty1.setText("1");

        AssemblerEmployeeQttyLess1.setText("-");
        AssemblerEmployeeQttyLess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssemblerEmployeeQttyLess1ActionPerformed(evt);
            }
        });

        AssemblerEmployeeQttyPlus1.setText("+");
        AssemblerEmployeeQttyPlus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssemblerEmployeeQttyPlus1ActionPerformed(evt);
            }
        });

        EmployeeQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        EmployeeQttyTitle1.setText("Cantidad de empleados:");

        BodyworksEmployeeQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BodyworksEmployeeQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BodyworksEmployeeQttyTitle1.setText("Empleados en carrocería");

        MotorsEmployeeQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MotorsEmployeeQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MotorsEmployeeQttyTitle1.setText("Empleados en motor");

        WheelsEmployeeQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WheelsEmployeeQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WheelsEmployeeQttyTitle1.setText("Empleados en ruedas");

        AccessoriesEmployeeQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesEmployeeQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessoriesEmployeeQttyTitle1.setText("Empleados en accesorios");

        PlantDirectorJob1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PlantDirectorJob1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlantDirectorJob1.setText("Trabajando");

        ChasisQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChasisQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChasisQtty1.setText(Integer.toString(this.maserati.getPartsWarehouse().getChasisDone()));

        StandardCarsQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StandardCarsQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        StandardCarsQttyTitle1.setText("Carros estándar:");

        BodyworksQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BodyworksQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BodyworksQtty1.setText(Integer.toString(this.maserati.getPartsWarehouse().getBodyworksDone()));

        MotorsQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MotorsQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MotorsQtty1.setText(Integer.toString(this.maserati.getPartsWarehouse().getMotorsDone()));

        WheelsQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WheelsQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WheelsQtty1.setText(Integer.toString(this.maserati.getPartsWarehouse().getWheelsDone()));

        AccessoriesQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessoriesQtty1.setText(Integer.toString(this.maserati.getPartsWarehouse().getAccessoriesDone()));

        StandardCarsQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StandardCarsQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StandardCarsQtty1.setText("1");

        BodyworksQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BodyworksQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BodyworksQttyTitle1.setText("Carrocerías:");

        MotorsQttyTitles1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MotorsQttyTitles1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MotorsQttyTitles1.setText("Motores:");

        WheelsQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WheelsQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        WheelsQttyTitle1.setText("Ruedas:");

        AccessoriesQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        AccessoriesQttyTitle1.setText("Accesorios:");

        MaxAccessoriesQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxAccessoriesQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MaxAccessoriesQttyTitle1.setText("Máx.");

        AccessoriesCarsQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesCarsQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        AccessoriesCarsQttyTitle1.setText("Carros con accesorios:");

        AccessoriesCarsQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AccessoriesCarsQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccessoriesCarsQtty1.setText("1");

        ChasisQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChasisQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ChasisQttyTitle1.setText("Chasis:");

        MaxChasisQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxChasisQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MaxChasisQttyTitle1.setText("Máx.");

        MaxBodyworksQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxBodyworksQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MaxBodyworksQttyTitle1.setText("Máx.");

        MaxMotorsQttyTitles1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxMotorsQttyTitles1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MaxMotorsQttyTitles1.setText("Máx.");

        MaxWheelsQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxWheelsQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MaxWheelsQttyTitle1.setText("Máx.");

        MaxChasisQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxChasisQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxChasisQtty1.setText(Integer.toString(this.maserati.getPartsWarehouse().getLimitChasis()));

        MaxBodyworksQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxBodyworksQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxBodyworksQtty1.setText(Integer.toString(this.maserati.getPartsWarehouse().getLimitBodyworks()));

        MaxMotorsQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxMotorsQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxMotorsQtty1.setText(Integer.toString(this.maserati.getPartsWarehouse().getLimitMotors()));

        MaxWheelsQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxWheelsQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxWheelsQtty1.setText(Integer.toString(this.maserati.getPartsWarehouse().getLimitWheels()));

        MaxAccessoriesQtty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaxAccessoriesQtty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxAccessoriesQtty1.setText(Integer.toString(this.maserati.getPartsWarehouse().getLimitAccessories()));

        DaysLeft1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DaysLeft1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaysLeft1.setText("0");

        PlantTitle1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        PlantTitle1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PlantTitle1.setText("Maserati");

        DaysLeftTitle1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DaysLeftTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DaysLeftTitle1.setText("Días para la entrega:");

        OpManagerTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        OpManagerTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpManagerTitle1.setText("Gerente de operaciones");

        EmployeeTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EmployeeTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeTitle1.setText("Empleados");

        PlantDirectorTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PlantDirectorTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlantDirectorTitle1.setText("Director de la planta");

        ChasisEmployeeQttyTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChasisEmployeeQttyTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChasisEmployeeQttyTitle1.setText("Empleados en chasis");

        PlantDirectorJobTitle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PlantDirectorJobTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlantDirectorJobTitle1.setText("¿Qué está haciendo?");

        OpManagerJob1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpManagerJob1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpManagerJob1.setText("Trabajando");

        OpManagerJobTitle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OpManagerJobTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpManagerJobTitle1.setText("¿Qué está haciendo?");

        OpManagerFaults1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpManagerFaults1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpManagerFaults1.setText("0");

        OpManagerFaultsTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpManagerFaultsTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        OpManagerFaultsTitle1.setText("Faltas:");

        OpManagerMoneyTaken1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpManagerMoneyTaken1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpManagerMoneyTaken1.setText("0");

        OpManagerMoneyTakenTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpManagerMoneyTakenTitle1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        OpManagerMoneyTakenTitle1.setText("Dinero descontado:");

        WarehouseTitle2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        WarehouseTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WarehouseTitle2.setText("Almacén");

        javax.swing.GroupLayout MaseratiLayout = new javax.swing.GroupLayout(Maserati);
        Maserati.setLayout(MaseratiLayout);
        MaseratiLayout.setHorizontalGroup(
            MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MaseratiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(PlantTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(450, 450, 450)
                            .addComponent(DaysLeftTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(DaysLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addComponent(WarehouseTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(PlantDirectorTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(EmployeeTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(ChasisQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(ChasisQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(MaxChasisQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(MaxChasisQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(PlantDirectorJobTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(150, 150, 150)
                            .addComponent(EmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(EmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(BodyworksQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(BodyworksQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(MaxBodyworksQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(MaxBodyworksQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(PlantDirectorJob1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(ChasisEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(ChasisEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(ChasisEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(ChasisEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(MotorsQttyTitles1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(MotorsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(MaxMotorsQttyTitles1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(MaxMotorsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(OpManagerTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(BodyworksEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(BodyworksEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(BodyworksEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(BodyworksEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(WheelsQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(WheelsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(MaxWheelsQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(MaxWheelsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(OpManagerJobTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(MotorsEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(MotorsEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(MotorsEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(MotorsEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(AccessoriesQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(AccessoriesQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(MaxAccessoriesQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(MaxAccessoriesQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(OpManagerJob1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(WheelsEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(WheelsEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(WheelsEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(WheelsEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(MaseratiLayout.createSequentialGroup()
                                    .addComponent(AccessoriesCarsQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(AccessoriesCarsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90)
                                    .addComponent(OpManagerMoneyTakenTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(OpManagerMoneyTaken1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(MaseratiLayout.createSequentialGroup()
                                    .addComponent(StandardCarsQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(StandardCarsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90)
                                    .addComponent(OpManagerFaultsTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(OpManagerFaults1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(140, 140, 140)
                            .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(MaseratiLayout.createSequentialGroup()
                                    .addComponent(AccessoriesEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(AccessoriesEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(AccessoriesEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(AccessoriesEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaseratiLayout.createSequentialGroup()
                                    .addComponent(AssemblerEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(AssemblerEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(AssemblerEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(AssemblerEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        MaseratiLayout.setVerticalGroup(
            MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MaseratiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PlantTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DaysLeftTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DaysLeft1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(WarehouseTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PlantDirectorTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmployeeTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ChasisQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ChasisQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaxChasisQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaxChasisQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PlantDirectorJobTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(BodyworksQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(BodyworksQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(MaxBodyworksQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(MaxBodyworksQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(PlantDirectorJob1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(ChasisEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(ChasisEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(ChasisEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(ChasisEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MotorsQttyTitles1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MotorsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaxMotorsQttyTitles1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaxMotorsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OpManagerTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BodyworksEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BodyworksEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BodyworksEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BodyworksEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(WheelsQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WheelsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaxWheelsQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaxWheelsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(OpManagerJobTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(MotorsEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(MotorsEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(MotorsEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(MotorsEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AccessoriesQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AccessoriesQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaxAccessoriesQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaxAccessoriesQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OpManagerJob1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(WheelsEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WheelsEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WheelsEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WheelsEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(10, 10, 10)
                    .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(OpManagerFaultsTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OpManagerFaults1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StandardCarsQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StandardCarsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AccessoriesEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AccessoriesEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AccessoriesEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AccessoriesEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(OpManagerMoneyTakenTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OpManagerMoneyTaken1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MaseratiLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(MaseratiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AccessoriesCarsQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AccessoriesCarsQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AssemblerEmployeeQttyTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AssemblerEmployeeQttyLess1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AssemblerEmployeeQtty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AssemblerEmployeeQttyPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab3", Maserati);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 1030, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1134, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void ChasisEmployeeQttyLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChasisEmployeeQttyLessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChasisEmployeeQttyLessActionPerformed

    private void ChasisEmployeeQttyPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChasisEmployeeQttyPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChasisEmployeeQttyPlusActionPerformed

    private void BodyworksEmployeeQttyLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodyworksEmployeeQttyLessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BodyworksEmployeeQttyLessActionPerformed

    private void BodyworksEmployeeQttyPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodyworksEmployeeQttyPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BodyworksEmployeeQttyPlusActionPerformed

    private void MotorsEmployeeQttyLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorsEmployeeQttyLessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotorsEmployeeQttyLessActionPerformed

    private void MotorsEmployeeQttyPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorsEmployeeQttyPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotorsEmployeeQttyPlusActionPerformed

    private void WheelsEmployeeQttyLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheelsEmployeeQttyLessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WheelsEmployeeQttyLessActionPerformed

    private void WheelsEmployeeQttyPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheelsEmployeeQttyPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WheelsEmployeeQttyPlusActionPerformed

    private void AccessoriesEmployeeQttyLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessoriesEmployeeQttyLessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccessoriesEmployeeQttyLessActionPerformed

    private void AccessoriesEmployeeQttyPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessoriesEmployeeQttyPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccessoriesEmployeeQttyPlusActionPerformed

    private void AssemblerEmployeeQttyLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssemblerEmployeeQttyLessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssemblerEmployeeQttyLessActionPerformed

    private void AssemblerEmployeeQttyPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssemblerEmployeeQttyPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssemblerEmployeeQttyPlusActionPerformed

    private void ChasisEmployeeQttyLess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChasisEmployeeQttyLess1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChasisEmployeeQttyLess1ActionPerformed

    private void ChasisEmployeeQttyPlus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChasisEmployeeQttyPlus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChasisEmployeeQttyPlus1ActionPerformed

    private void BodyworksEmployeeQttyLess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodyworksEmployeeQttyLess1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BodyworksEmployeeQttyLess1ActionPerformed

    private void BodyworksEmployeeQttyPlus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BodyworksEmployeeQttyPlus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BodyworksEmployeeQttyPlus1ActionPerformed

    private void MotorsEmployeeQttyLess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorsEmployeeQttyLess1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotorsEmployeeQttyLess1ActionPerformed

    private void MotorsEmployeeQttyPlus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorsEmployeeQttyPlus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotorsEmployeeQttyPlus1ActionPerformed

    private void WheelsEmployeeQttyLess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheelsEmployeeQttyLess1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WheelsEmployeeQttyLess1ActionPerformed

    private void WheelsEmployeeQttyPlus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheelsEmployeeQttyPlus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WheelsEmployeeQttyPlus1ActionPerformed

    private void AccessoriesEmployeeQttyLess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessoriesEmployeeQttyLess1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccessoriesEmployeeQttyLess1ActionPerformed

    private void AccessoriesEmployeeQttyPlus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessoriesEmployeeQttyPlus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccessoriesEmployeeQttyPlus1ActionPerformed

    private void AssemblerEmployeeQttyLess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssemblerEmployeeQttyLess1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssemblerEmployeeQttyLess1ActionPerformed

    private void AssemblerEmployeeQttyPlus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssemblerEmployeeQttyPlus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssemblerEmployeeQttyPlus1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccessoriesCarsQtty;
    private javax.swing.JLabel AccessoriesCarsQtty1;
    private javax.swing.JLabel AccessoriesCarsQttyTitle;
    private javax.swing.JLabel AccessoriesCarsQttyTitle1;
    private javax.swing.JLabel AccessoriesEmployeeQtty;
    private javax.swing.JLabel AccessoriesEmployeeQtty1;
    private javax.swing.JButton AccessoriesEmployeeQttyLess;
    private javax.swing.JButton AccessoriesEmployeeQttyLess1;
    private javax.swing.JButton AccessoriesEmployeeQttyPlus;
    private javax.swing.JButton AccessoriesEmployeeQttyPlus1;
    private javax.swing.JLabel AccessoriesEmployeeQttyTitle;
    private javax.swing.JLabel AccessoriesEmployeeQttyTitle1;
    private javax.swing.JLabel AccessoriesQtty;
    private javax.swing.JLabel AccessoriesQtty1;
    private javax.swing.JLabel AccessoriesQttyTitle;
    private javax.swing.JLabel AccessoriesQttyTitle1;
    private javax.swing.JLabel AssemblerEmployeeQtty;
    private javax.swing.JLabel AssemblerEmployeeQtty1;
    private javax.swing.JButton AssemblerEmployeeQttyLess;
    private javax.swing.JButton AssemblerEmployeeQttyLess1;
    private javax.swing.JButton AssemblerEmployeeQttyPlus;
    private javax.swing.JButton AssemblerEmployeeQttyPlus1;
    private javax.swing.JLabel AssemblerEmployeeQttyTitle;
    private javax.swing.JLabel AssemblerEmployeeQttyTitle1;
    private javax.swing.JLabel BodyworksEmployeeQtty;
    private javax.swing.JLabel BodyworksEmployeeQtty1;
    private javax.swing.JButton BodyworksEmployeeQttyLess;
    private javax.swing.JButton BodyworksEmployeeQttyLess1;
    private javax.swing.JButton BodyworksEmployeeQttyPlus;
    private javax.swing.JButton BodyworksEmployeeQttyPlus1;
    private javax.swing.JLabel BodyworksEmployeeQttyTitle;
    private javax.swing.JLabel BodyworksEmployeeQttyTitle1;
    private javax.swing.JLabel BodyworksQtty;
    private javax.swing.JLabel BodyworksQtty1;
    private javax.swing.JLabel BodyworksQttyTitle;
    private javax.swing.JLabel BodyworksQttyTitle1;
    private javax.swing.JPanel Bugatti;
    private javax.swing.JLabel ChasisEmployeeQtty;
    private javax.swing.JLabel ChasisEmployeeQtty1;
    private javax.swing.JButton ChasisEmployeeQttyLess;
    private javax.swing.JButton ChasisEmployeeQttyLess1;
    private javax.swing.JButton ChasisEmployeeQttyPlus;
    private javax.swing.JButton ChasisEmployeeQttyPlus1;
    private javax.swing.JLabel ChasisEmployeeQttyTitle;
    private javax.swing.JLabel ChasisEmployeeQttyTitle1;
    private javax.swing.JLabel ChasisQtty;
    private javax.swing.JLabel ChasisQtty1;
    private javax.swing.JLabel ChasisQttyTitle;
    private javax.swing.JLabel ChasisQttyTitle1;
    private javax.swing.JLabel DaysLeft;
    private javax.swing.JLabel DaysLeft1;
    private javax.swing.JLabel DaysLeftTitle;
    private javax.swing.JLabel DaysLeftTitle1;
    private javax.swing.JLabel EmployeeQtty;
    private javax.swing.JLabel EmployeeQtty1;
    private javax.swing.JLabel EmployeeQttyTitle;
    private javax.swing.JLabel EmployeeQttyTitle1;
    private javax.swing.JLabel EmployeeTitle;
    private javax.swing.JLabel EmployeeTitle1;
    private javax.swing.JPanel Maserati;
    private javax.swing.JLabel MaxAccessoriesQtty;
    private javax.swing.JLabel MaxAccessoriesQtty1;
    private javax.swing.JLabel MaxAccessoriesQttyTitle;
    private javax.swing.JLabel MaxAccessoriesQttyTitle1;
    private javax.swing.JLabel MaxBodyworksQtty;
    private javax.swing.JLabel MaxBodyworksQtty1;
    private javax.swing.JLabel MaxBodyworksQttyTitle;
    private javax.swing.JLabel MaxBodyworksQttyTitle1;
    private javax.swing.JLabel MaxChasisQtty;
    private javax.swing.JLabel MaxChasisQtty1;
    private javax.swing.JLabel MaxChasisQttyTitle;
    private javax.swing.JLabel MaxChasisQttyTitle1;
    private javax.swing.JLabel MaxMotorsQtty;
    private javax.swing.JLabel MaxMotorsQtty1;
    private javax.swing.JLabel MaxMotorsQttyTitles;
    private javax.swing.JLabel MaxMotorsQttyTitles1;
    private javax.swing.JLabel MaxWheelsQtty;
    private javax.swing.JLabel MaxWheelsQtty1;
    private javax.swing.JLabel MaxWheelsQttyTitle;
    private javax.swing.JLabel MaxWheelsQttyTitle1;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel MotorsEmployeeQtty;
    private javax.swing.JLabel MotorsEmployeeQtty1;
    private javax.swing.JButton MotorsEmployeeQttyLess;
    private javax.swing.JButton MotorsEmployeeQttyLess1;
    private javax.swing.JButton MotorsEmployeeQttyPlus;
    private javax.swing.JButton MotorsEmployeeQttyPlus1;
    private javax.swing.JLabel MotorsEmployeeQttyTitle;
    private javax.swing.JLabel MotorsEmployeeQttyTitle1;
    private javax.swing.JLabel MotorsQtty;
    private javax.swing.JLabel MotorsQtty1;
    private javax.swing.JLabel MotorsQttyTitles;
    private javax.swing.JLabel MotorsQttyTitles1;
    private javax.swing.JLabel OpManagerFaults;
    private javax.swing.JLabel OpManagerFaults1;
    private javax.swing.JLabel OpManagerFaultsTitle;
    private javax.swing.JLabel OpManagerFaultsTitle1;
    private javax.swing.JLabel OpManagerJob;
    private javax.swing.JLabel OpManagerJob1;
    private javax.swing.JLabel OpManagerJobTitle;
    private javax.swing.JLabel OpManagerJobTitle1;
    private javax.swing.JLabel OpManagerMoneyTaken;
    private javax.swing.JLabel OpManagerMoneyTaken1;
    private javax.swing.JLabel OpManagerMoneyTakenTitle;
    private javax.swing.JLabel OpManagerMoneyTakenTitle1;
    private javax.swing.JLabel OpManagerTitle;
    private javax.swing.JLabel OpManagerTitle1;
    private javax.swing.JLabel PlantDirectorJob;
    private javax.swing.JLabel PlantDirectorJob1;
    private javax.swing.JLabel PlantDirectorJobTitle;
    private javax.swing.JLabel PlantDirectorJobTitle1;
    private javax.swing.JLabel PlantDirectorTitle;
    private javax.swing.JLabel PlantDirectorTitle1;
    private javax.swing.JLabel PlantTitle;
    private javax.swing.JLabel PlantTitle1;
    private javax.swing.JLabel StandardCarsQtty;
    private javax.swing.JLabel StandardCarsQtty1;
    private javax.swing.JLabel StandardCarsQttyTitle;
    private javax.swing.JLabel StandardCarsQttyTitle1;
    private javax.swing.JLabel WarehouseTitle1;
    private javax.swing.JLabel WarehouseTitle2;
    private javax.swing.JLabel WheelsEmployeeQtty;
    private javax.swing.JLabel WheelsEmployeeQtty1;
    private javax.swing.JButton WheelsEmployeeQttyLess;
    private javax.swing.JButton WheelsEmployeeQttyLess1;
    private javax.swing.JButton WheelsEmployeeQttyPlus;
    private javax.swing.JButton WheelsEmployeeQttyPlus1;
    private javax.swing.JLabel WheelsEmployeeQttyTitle;
    private javax.swing.JLabel WheelsEmployeeQttyTitle1;
    private javax.swing.JLabel WheelsQtty;
    private javax.swing.JLabel WheelsQtty1;
    private javax.swing.JLabel WheelsQttyTitle;
    private javax.swing.JLabel WheelsQttyTitle1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
